### PR TITLE
Added column "Continent_7"

### PR DESCRIPTION
**Pull request by marthhoi**
Added a column "Continent_7" to country_data.tsv where countries are allocated to 7 continents according to
https://ourworldindata.org/world-region-map-definitions

### CODE REVIEW

**Comment by konstantinstadler** [comment]
Hi Marta, you said there was also something wrong with one of the other classifications? Did you fix that as well?

**Comment by marthhoi** [comment]
I noticed that the territory of Heard Island and McDonald Islands was classified as "Asia" which does not seem right, but I did not modify it as I wasn't sure which source the continent classification was based on / where to assign it. It's an Australian territory but I think it is often classified as Antarctica.

**Comment by konstantinstadler** [comment]
Ah, ok. Just leave it, I will fix that

________________________________

**Review by konstantinstadler — APPROVED** [review]

**Comment by konstantinstadler** [comment]
Looks good, thanks. Will release the update in the next days

**Pull request merged**
