### PR TITLE
Bonsai

### PR DESCRIPTION
**Pull request by mabudz**
The PR adds the following synonyms to existing classifications:

to `ISOnumeric`:
- [BACI](https://www.cepii.fr/CEPII/en/bdd_modele/bdd_modele_item.asp?id=37) - BACI: International Trade Database at the Product-Level
- [UNIDO](https://stat.unido.org/portal/dataset/getDataset/COUNTRY_PROFILE) - UNIDO INDSTAT database

to `EXIO3`:
- [EXIOBASE hybrid 3](https://zenodo.org/records/10148587) classification
- [EXIOBASE hybrid 3 consequential](https://zenodo.org/records/13926939) classification

Furthermore, a new classification `GEOnumeric` has been added:
- [GEOnumeric](https://ec.europa.eu/eurostat/comext/newxtweb/openNom.do) GEO numerical codes (also used in Prodcom)

Since the original codes for GEOnumeric is a 4-digit, which starts with "0", I decided to treat those as strings in coco.

### CODE REVIEW

**Review by konstantinstadler — APPROVED** [review]

**Comment by konstantinstadler** [comment]
Hi, changes in the files are ok, but it seems you did not run the linter before submitting (isort and black)

**Comment by mabudz** [comment]
please do not merge, we found and issue that we want to fix

**Comment by konstantinstadler** [comment]
sure, please let me know when it is ready

**Comment by mabudz** [comment]
I pushed some updates to fix an issue on how coco was dealing with the numerical codes. In the previous version of coco all the codes were returned as `floats` when doing like that:
```
cc = coco.CountryConverter()
gbd_codes = cc.GBDcode.GBDcode
```

However, I would expect that all codes are `integers` so that `coco.convert(gbd_codes ,src="GBDcode", to="ISO2")` works without having all "not found" inside the series.

So, I revised in that regard.

Furthermore, the newly added `GEOnumeric` codes are now also treated as integers instead of strings. This makes it obsolete to add other classifications that are using "001" instead of "0001".

**Comment by konstantinstadler** [comment]
Great, thanks a lot @mabudz

**Pull request merged**
